set(_vtk_module_import_prefix "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
get_filename_component(_vtk_module_import_prefix "${_vtk_module_import_prefix}" DIRECTORY)
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_include_marshal" "FALSE")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_depends" "vtkCGALAlgorithm;vtkCGALPSP")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_library_name" "vtkCGALSR")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkCGALPoissonSurfaceReconstructionDelaunay.h;${_vtk_module_import_prefix}/include/vtkCGALAdvancingFrontSurfaceReconstruction.h")
set_property(TARGET "vtkCGALSR" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vespa/vtkCGALSR-hierarchy.txt")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_include_marshal" "FALSE")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_depends" "vtkCGALAlgorithm")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_library_name" "vtkCGALPMP")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkCGALBooleanOperation.h;${_vtk_module_import_prefix}/include/vtkCGALIsotropicRemesher.h;${_vtk_module_import_prefix}/include/vtkCGALMeshChecker.h;${_vtk_module_import_prefix}/include/vtkCGALMeshDeformation.h;${_vtk_module_import_prefix}/include/vtkCGALMeshSubdivision.h;${_vtk_module_import_prefix}/include/vtkCGALPatchFilling.h;${_vtk_module_import_prefix}/include/vtkCGALRegionFairing.h;${_vtk_module_import_prefix}/include/vtkCGALShapeSmoothing.h;${_vtk_module_import_prefix}/include/vtkCGALSignedDistanceFunction.h;${_vtk_module_import_prefix}/include/vtkCGALAlphaWrapping.h;${_vtk_module_import_prefix}/include/vtkCGALMeshSmoothing.h")
set_property(TARGET "vtkCGALPMP" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vespa/vtkCGALPMP-hierarchy.txt")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_include_marshal" "FALSE")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_depends" "vtkCGALAlgorithm")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_library_name" "vtkCGALPSP")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkCGALPCAEstimateNormals.h;${_vtk_module_import_prefix}/include/vtkCGALXYZReader.h")
set_property(TARGET "vtkCGALPSP" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vespa/vtkCGALPSP-hierarchy.txt")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_include_marshal" "FALSE")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_depends" "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeometry;CGAL::CGAL")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_library_name" "vtkCGALDelaunay")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkCGALDelaunay2.h")
set_property(TARGET "vtkCGALDelaunay" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vespa/vtkCGALDelaunay-hierarchy.txt")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_exclude_wrap" "FALSE")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_include_marshal" "FALSE")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_depends" "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeometry;CGAL::CGAL")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_private_depends" "")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_optional_depends" "")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_implements" "")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_implementable" "FALSE")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_library_name" "vtkCGALAlgorithm")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_headers" "${_vtk_module_import_prefix}/include/vtkCGALHelper.h;${_vtk_module_import_prefix}/include/vtkCGALPolyDataAlgorithm.h;${_vtk_module_import_prefix}/include/vtkCGALHelper.h")
set_property(TARGET "vtkCGALAlgorithm" PROPERTY "INTERFACE_vtk_module_hierarchy" "${_vtk_module_import_prefix}/lib/vtk/hierarchy/vespa/vtkCGALAlgorithm-hierarchy.txt")
unset(_vtk_module_import_prefix)
