// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_roundtrip
Rcpp::List rcpp_roundtrip(Rcpp::List mesh);
RcppExport SEXP _vespa_rcpp_roundtrip(SEXP meshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_roundtrip(mesh));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_delaunay2
Rcpp::List rcpp_delaunay2(Rcpp::NumericMatrix points, Rcpp::Nullable<Rcpp::IntegerMatrix> constraint_edges);
RcppExport SEXP _vespa_rcpp_delaunay2(SEXP pointsSEXP, SEXP constraint_edgesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerMatrix> >::type constraint_edges(constraint_edgesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_delaunay2(points, constraint_edges));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_alpha_wrap
Rcpp::List rcpp_alpha_wrap(Rcpp::List mesh, double alpha, double offset, bool absolute_thresholds, bool update_attributes);
RcppExport SEXP _vespa_rcpp_alpha_wrap(SEXP meshSEXP, SEXP alphaSEXP, SEXP offsetSEXP, SEXP absolute_thresholdsSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type absolute_thresholds(absolute_thresholdsSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_alpha_wrap(mesh, alpha, offset, absolute_thresholds, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mesh_smooth
Rcpp::List rcpp_mesh_smooth(Rcpp::List mesh, unsigned int method, unsigned int n_iterations, bool safety_constraints, bool update_attributes);
RcppExport SEXP _vespa_rcpp_mesh_smooth(SEXP meshSEXP, SEXP methodSEXP, SEXP n_iterationsSEXP, SEXP safety_constraintsSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type safety_constraints(safety_constraintsSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mesh_smooth(mesh, method, n_iterations, safety_constraints, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_subdivide
Rcpp::List rcpp_subdivide(Rcpp::List mesh, int subdivision_type, unsigned int n_iterations, bool update_attributes);
RcppExport SEXP _vespa_rcpp_subdivide(SEXP meshSEXP, SEXP subdivision_typeSEXP, SEXP n_iterationsSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< int >::type subdivision_type(subdivision_typeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_subdivide(mesh, subdivision_type, n_iterations, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_shape_smooth
Rcpp::List rcpp_shape_smooth(Rcpp::List mesh, unsigned int n_iterations, double time_step, bool update_attributes);
RcppExport SEXP _vespa_rcpp_shape_smooth(SEXP meshSEXP, SEXP n_iterationsSEXP, SEXP time_stepSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type time_step(time_stepSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_shape_smooth(mesh, n_iterations, time_step, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mesh_check
Rcpp::List rcpp_mesh_check(Rcpp::List mesh, bool check_watertight, bool check_intersect, bool attempt_repair);
RcppExport SEXP _vespa_rcpp_mesh_check(SEXP meshSEXP, SEXP check_watertightSEXP, SEXP check_intersectSEXP, SEXP attempt_repairSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< bool >::type check_watertight(check_watertightSEXP);
    Rcpp::traits::input_parameter< bool >::type check_intersect(check_intersectSEXP);
    Rcpp::traits::input_parameter< bool >::type attempt_repair(attempt_repairSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mesh_check(mesh, check_watertight, check_intersect, attempt_repair));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_isotropic_remesh
Rcpp::List rcpp_isotropic_remesh(Rcpp::List mesh, double target_length, double protect_angle, int n_iterations, bool update_attributes);
RcppExport SEXP _vespa_rcpp_isotropic_remesh(SEXP meshSEXP, SEXP target_lengthSEXP, SEXP protect_angleSEXP, SEXP n_iterationsSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< double >::type target_length(target_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type protect_angle(protect_angleSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_isotropic_remesh(mesh, target_length, protect_angle, n_iterations, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_boolean_op
Rcpp::List rcpp_boolean_op(Rcpp::List mesh_a, Rcpp::List mesh_b, int operation, bool update_attributes);
RcppExport SEXP _vespa_rcpp_boolean_op(SEXP mesh_aSEXP, SEXP mesh_bSEXP, SEXP operationSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh_a(mesh_aSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh_b(mesh_bSEXP);
    Rcpp::traits::input_parameter< int >::type operation(operationSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_boolean_op(mesh_a, mesh_b, operation, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_patch_fill
Rcpp::List rcpp_patch_fill(Rcpp::List mesh, Rcpp::IntegerVector point_ids, int fairing_continuity, bool update_attributes);
RcppExport SEXP _vespa_rcpp_patch_fill(SEXP meshSEXP, SEXP point_idsSEXP, SEXP fairing_continuitySEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type point_ids(point_idsSEXP);
    Rcpp::traits::input_parameter< int >::type fairing_continuity(fairing_continuitySEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_patch_fill(mesh, point_ids, fairing_continuity, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_region_fair
Rcpp::List rcpp_region_fair(Rcpp::List mesh, Rcpp::IntegerVector point_ids, bool update_attributes);
RcppExport SEXP _vespa_rcpp_region_fair(SEXP meshSEXP, SEXP point_idsSEXP, SEXP update_attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type point_ids(point_idsSEXP);
    Rcpp::traits::input_parameter< bool >::type update_attributes(update_attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_region_fair(mesh, point_ids, update_attributes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_mesh_deform
Rcpp::List rcpp_mesh_deform(Rcpp::List mesh, Rcpp::IntegerVector control_ids, Rcpp::NumericMatrix target_coords, Rcpp::IntegerVector roi_ids, int mode, double sre_alpha, unsigned int n_iterations, double tolerance);
RcppExport SEXP _vespa_rcpp_mesh_deform(SEXP meshSEXP, SEXP control_idsSEXP, SEXP target_coordsSEXP, SEXP roi_idsSEXP, SEXP modeSEXP, SEXP sre_alphaSEXP, SEXP n_iterationsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type control_ids(control_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type target_coords(target_coordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type roi_ids(roi_idsSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type sre_alpha(sre_alphaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_mesh_deform(mesh, control_ids, target_coords, roi_ids, mode, sre_alpha, n_iterations, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sdf
Rcpp::List rcpp_sdf(Rcpp::List mesh, unsigned int base_resolution, int padding);
RcppExport SEXP _vespa_rcpp_sdf(SEXP meshSEXP, SEXP base_resolutionSEXP, SEXP paddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type base_resolution(base_resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type padding(paddingSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sdf(mesh, base_resolution, padding));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pca_normals
Rcpp::List rcpp_pca_normals(Rcpp::List mesh, unsigned int n_neighbors, bool orient, bool delete_unoriented);
RcppExport SEXP _vespa_rcpp_pca_normals(SEXP meshSEXP, SEXP n_neighborsSEXP, SEXP orientSEXP, SEXP delete_unorientedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_neighbors(n_neighborsSEXP);
    Rcpp::traits::input_parameter< bool >::type orient(orientSEXP);
    Rcpp::traits::input_parameter< bool >::type delete_unoriented(delete_unorientedSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pca_normals(mesh, n_neighbors, orient, delete_unoriented));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_read_points
Rcpp::List rcpp_read_points(std::string filename);
RcppExport SEXP _vespa_rcpp_read_points(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_read_points(filename));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_poisson_recon
Rcpp::List rcpp_poisson_recon(Rcpp::List mesh, double min_angle, double max_size, double distance, bool gen_normals);
RcppExport SEXP _vespa_rcpp_poisson_recon(SEXP meshSEXP, SEXP min_angleSEXP, SEXP max_sizeSEXP, SEXP distanceSEXP, SEXP gen_normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< double >::type min_angle(min_angleSEXP);
    Rcpp::traits::input_parameter< double >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< bool >::type gen_normals(gen_normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_poisson_recon(mesh, min_angle, max_size, distance, gen_normals));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_advancing_front
Rcpp::List rcpp_advancing_front(Rcpp::List mesh, double per, double radius_ratio_bound);
RcppExport SEXP _vespa_rcpp_advancing_front(SEXP meshSEXP, SEXP perSEXP, SEXP radius_ratio_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type mesh(meshSEXP);
    Rcpp::traits::input_parameter< double >::type per(perSEXP);
    Rcpp::traits::input_parameter< double >::type radius_ratio_bound(radius_ratio_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_advancing_front(mesh, per, radius_ratio_bound));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_vtk_available
bool rcpp_vtk_available();
RcppExport SEXP _vespa_rcpp_vtk_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_vtk_available());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vespa_rcpp_roundtrip", (DL_FUNC) &_vespa_rcpp_roundtrip, 1},
    {"_vespa_rcpp_delaunay2", (DL_FUNC) &_vespa_rcpp_delaunay2, 2},
    {"_vespa_rcpp_alpha_wrap", (DL_FUNC) &_vespa_rcpp_alpha_wrap, 5},
    {"_vespa_rcpp_mesh_smooth", (DL_FUNC) &_vespa_rcpp_mesh_smooth, 5},
    {"_vespa_rcpp_subdivide", (DL_FUNC) &_vespa_rcpp_subdivide, 4},
    {"_vespa_rcpp_shape_smooth", (DL_FUNC) &_vespa_rcpp_shape_smooth, 4},
    {"_vespa_rcpp_mesh_check", (DL_FUNC) &_vespa_rcpp_mesh_check, 4},
    {"_vespa_rcpp_isotropic_remesh", (DL_FUNC) &_vespa_rcpp_isotropic_remesh, 5},
    {"_vespa_rcpp_boolean_op", (DL_FUNC) &_vespa_rcpp_boolean_op, 4},
    {"_vespa_rcpp_patch_fill", (DL_FUNC) &_vespa_rcpp_patch_fill, 4},
    {"_vespa_rcpp_region_fair", (DL_FUNC) &_vespa_rcpp_region_fair, 3},
    {"_vespa_rcpp_mesh_deform", (DL_FUNC) &_vespa_rcpp_mesh_deform, 8},
    {"_vespa_rcpp_sdf", (DL_FUNC) &_vespa_rcpp_sdf, 3},
    {"_vespa_rcpp_pca_normals", (DL_FUNC) &_vespa_rcpp_pca_normals, 4},
    {"_vespa_rcpp_read_points", (DL_FUNC) &_vespa_rcpp_read_points, 1},
    {"_vespa_rcpp_poisson_recon", (DL_FUNC) &_vespa_rcpp_poisson_recon, 5},
    {"_vespa_rcpp_advancing_front", (DL_FUNC) &_vespa_rcpp_advancing_front, 3},
    {"_vespa_rcpp_vtk_available", (DL_FUNC) &_vespa_rcpp_vtk_available, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_vespa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
