# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_roundtrip <- function(mesh) {
    .Call(`_vespa_rcpp_roundtrip`, mesh)
}

rcpp_delaunay2 <- function(points, constraint_edges = NULL) {
    .Call(`_vespa_rcpp_delaunay2`, points, constraint_edges)
}

rcpp_alpha_wrap <- function(mesh, alpha = 5.0, offset = 3.0, absolute_thresholds = FALSE, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_alpha_wrap`, mesh, alpha, offset, absolute_thresholds, update_attributes)
}

rcpp_mesh_smooth <- function(mesh, method = 1L, n_iterations = 10L, safety_constraints = FALSE, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_mesh_smooth`, mesh, method, n_iterations, safety_constraints, update_attributes)
}

rcpp_subdivide <- function(mesh, subdivision_type = 3L, n_iterations = 1L, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_subdivide`, mesh, subdivision_type, n_iterations, update_attributes)
}

rcpp_shape_smooth <- function(mesh, n_iterations = 1L, time_step = 1e-4, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_shape_smooth`, mesh, n_iterations, time_step, update_attributes)
}

rcpp_mesh_check <- function(mesh, check_watertight = TRUE, check_intersect = TRUE, attempt_repair = FALSE) {
    .Call(`_vespa_rcpp_mesh_check`, mesh, check_watertight, check_intersect, attempt_repair)
}

rcpp_isotropic_remesh <- function(mesh, target_length = -1.0, protect_angle = 45.0, n_iterations = 1L, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_isotropic_remesh`, mesh, target_length, protect_angle, n_iterations, update_attributes)
}

rcpp_boolean_op <- function(mesh_a, mesh_b, operation = 0L, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_boolean_op`, mesh_a, mesh_b, operation, update_attributes)
}

rcpp_patch_fill <- function(mesh, point_ids, fairing_continuity = 1L, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_patch_fill`, mesh, point_ids, fairing_continuity, update_attributes)
}

rcpp_region_fair <- function(mesh, point_ids, update_attributes = TRUE) {
    .Call(`_vespa_rcpp_region_fair`, mesh, point_ids, update_attributes)
}

rcpp_mesh_deform <- function(mesh, control_ids, target_coords, roi_ids, mode = 0L, sre_alpha = 0.02, n_iterations = 5L, tolerance = 1e-4) {
    .Call(`_vespa_rcpp_mesh_deform`, mesh, control_ids, target_coords, roi_ids, mode, sre_alpha, n_iterations, tolerance)
}

rcpp_sdf <- function(mesh, base_resolution = 64L, padding = 0L) {
    .Call(`_vespa_rcpp_sdf`, mesh, base_resolution, padding)
}

rcpp_pca_normals <- function(mesh, n_neighbors = 18L, orient = TRUE, delete_unoriented = TRUE) {
    .Call(`_vespa_rcpp_pca_normals`, mesh, n_neighbors, orient, delete_unoriented)
}

rcpp_read_points <- function(filename) {
    .Call(`_vespa_rcpp_read_points`, filename)
}

rcpp_poisson_recon <- function(mesh, min_angle = 20.0, max_size = 2.0, distance = 0.375, gen_normals = TRUE) {
    .Call(`_vespa_rcpp_poisson_recon`, mesh, min_angle, max_size, distance, gen_normals)
}

rcpp_advancing_front <- function(mesh, per = 0.0, radius_ratio_bound = 5.0) {
    .Call(`_vespa_rcpp_advancing_front`, mesh, per, radius_ratio_bound)
}

rcpp_vtk_available <- function() {
    .Call(`_vespa_rcpp_vtk_available`)
}

